name: calculatoraitdev
description: A simple package that adds 1 to any integer.
version: 0.0.1
homepage: https://github.com/kumaramitcpr121/first_package
repository: https://github.com/kumaramitcpr121/first_package
issue_tracker: https://github.com/kumaramitcpr121/first_package/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
